# BAS6 package for  MODFLOW-2005, generated by Flopy.
# Updated by Justin Clark, September 2025
#
FREE
INTERNAL               1    (20I10)  -1           #IBOUND Layer 1
         1         1         1         1         1         1         1         1         1         1         1         1         1         1         1         1         1         1         1         1
         1         1         1         1         1         1         1         1         1         1         1         1         1         1         1         1         1         1         1         1
         1         1         1         1         1         1         1         1         1         1         1         1         1         1         1         1         1         1         1         1
         1         1         1         1         1         1         1         1         1         1         1         1         1         1         1         1         1         1         1         1
         1         1         1         1         1         1         1         1         1         1         1         1         1         1         1         1         1         1         1         1
         1         1         1         1         1         1         1         1         1         1         1         1         1         1         1         1         1         1         1         1
         1         1         1         1         1         1         1         1         1         1         1         1         1         1         1         1         1         1         1         1
         1         1         1         1         1         1         1         1         1         1         1         1         1         1         1         1         1         1         1         1
         1         1         1         1         1         1         1         1         1         1         1         1         1         1         1         1         1         1         1         1
         1         1         1         1         1         1         1         1         1         1         1         1         1         1         1         1         1         1         1         1
   -999.99
CONSTANT    1.500000E+01                          #Head Start Layer 1
